# Site settings
title: The UK Web Archive
email: WebArchivist@bl.uk
description: UK Web Archive prototype web site.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://beta.webarchive.org.uk" # the base hostname & protocol for your site
twitter_username: UKWebArchive
github_username:  ukwa

# Build settings
markdown: kramdown
